### ISSUE TITLE
Etki Alanı Oluştur Sekmesi | Hatalar

### ISSUE THREAD

**Issue by zekiahmetbayar** [zekiahmetbayar/liman-sambahvl#12]
Etki Alanı Oluştur sekmesi testlerinde yaşanan görsel ve sistemsel hatalar :

- [x] Sayfa başına kırmızı hata mesajı konulmalı "Lütfen önce sambahvl paketini kurunuz !" 
- [x] Sambahvl kurulmadan da etki alanı oluştur butonu çalışıyor, kontrol eklenmeli
- [x] Etki alanı oluşturma smb.conf varlığına göre kontrol ediliyor, mekanizma geliştirilmeli
- [x] Etki alanı oluşturulurken kayıtları ekrana basmalı
- [x] Etki alanı oluşturulduktan sonra sayfa yenilenmeli, etki alanı güncel bilgileri ekrana basılmalı
- [x] Göç işlemi yapılmış etki alanı kontrolcülerinde, etki alanı bilgileri kısmı boş dönüyor.

**Comment by abugraokkali** [comment]
> Etki Alanı Oluştur sekmesi testlerinde yaşanan görsel ve sistemsel hatalar :
> 
> * [x]  Sayfa başına kırmızı hata mesajı konulmalı "Lütfen önce sambahvl paketini kurunuz !"
> * [x]  Sambahvl kurulmadan da etki alanı oluştur butonu çalışıyor, kontrol eklenmeli
> * [x]  Etki alanı oluşturma smb.conf varlığına göre kontrol ediliyor, mekanizma geliştirilmeli
> * [ ]  Etki alanı oluşturulurken kayıtları ekrana basmalı
> * [ ]  Etki alanı oluşturulduktan sonra sayfa yenilenmeli, etki alanı güncel bilgileri ekrana basılmalı
> * [x]  Göç işlemi yapılmış etki alanı kontrolcülerinde, etki alanı bilgileri kısmı boş dönüyor.
