### ISSUE TITLE
FSMO Rolleri Sekmesi | Hatalar

### ISSUE THREAD

**Issue by zekiahmetbayar** [zekiahmetbayar/liman-sambahvl#13]
FSMO Rolleri sekmesi testlerinde yaşanan görsel ve sistemsel hatalar :

- [x] Eğer sambahvl kurulu değilse kırmızı hata mesajı verilmeli "Lütfen önce sambahvl paketini kurunuz !"
- [x] Eğer sambahvl değilse butonlar kullanıma kapatılmalı
- [x] Tüm roller aynı dc de ise buton deaktif edilebilir
- [x] Belirli bir rolü al butonu kaldırılmalı, zaten sağ tık menüsünden yapılabiliyor

**Comment by abugraokkali** [comment]
> FSMO Rolleri sekmesi testlerinde yaşanan görsel ve sistemsel hatalar :
> 
> * [ ]  Eğer sambahvl kurulu değilse kırmızı hata mesajı verilmeli "Lütfen önce sambahvl paketini kurunuz !"
> * [ ]  Eğer sambahvl değilse butonlar kullanıma kapatılmalı
> * [ ]  Tüm roller aynı dc de ise buton deaktif edilebilir
> * [ x]  Belirli bir rolü al butonu kaldırılmalı, zaten sağ tık menüsünden yapılabiliyor
